/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	clusterprovisioner_v1alpha1 "github.com/rancher/kubecon2018/pkg/apis/clusterprovisioner/v1alpha1"
	versioned "github.com/rancher/kubecon2018/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rancher/kubecon2018/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/rancher/kubecon2018/pkg/client/listers/clusterprovisioner/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// KubeconfigInformer provides access to a shared informer and lister for
// Kubeconfigs.
type KubeconfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KubeconfigLister
}

type kubeconfigInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewKubeconfigInformer constructs a new informer for Kubeconfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeconfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.ClusterprovisionerV1alpha1().Kubeconfigs().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.ClusterprovisionerV1alpha1().Kubeconfigs().Watch(options)
			},
		},
		&clusterprovisioner_v1alpha1.Kubeconfig{},
		resyncPeriod,
		indexers,
	)
}

func defaultKubeconfigInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewKubeconfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *kubeconfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterprovisioner_v1alpha1.Kubeconfig{}, defaultKubeconfigInformer)
}

func (f *kubeconfigInformer) Lister() v1alpha1.KubeconfigLister {
	return v1alpha1.NewKubeconfigLister(f.Informer().GetIndexer())
}
